# Site settings
title: "Initializing variables..."
email: vrinek@me.com
description: "Tech blog. Ruby, game development, random."
baseurl: ""
url: "http://blog.vrinek.io"
username: "vrinek"

# Build settings
markdown: kramdown
permalink: pretty
